apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
  namespace: wg-vpn
type: Opaque
stringData:
  CORE_NODE_ID: "00000000-0000-0000-0000-000000000001"
  ADMIN_API_TOKEN: "replace_me_same_as_entry"
  WG_SERVER_PUBLIC_KEY: "replace_me"
  WG_PRIVATE_KEY_PATH: "/etc/wireguard/private.key"
  CORE_TLS_CERT_PATH: "/etc/core-tls/server.crt"
  CORE_TLS_KEY_PATH: "/etc/core-tls/server.key"
  CORE_TLS_CLIENT_CA_CERT_PATH: "/etc/core-tls/ca.pem"
