apiVersion: v1
kind: Secret
metadata:
  name: core-tls
  namespace: wg-vpn
type: Opaque
stringData:
  server.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_ME
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_ME
    -----END PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    REPLACE_ME
    -----END CERTIFICATE-----
