apiVersion: v1
kind: Secret
metadata:
  name: core-grpc-client-tls
  namespace: wg-vpn
type: Opaque
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    REPLACE_ME
    -----END CERTIFICATE-----
  client.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_ME
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_ME
    -----END PRIVATE KEY-----
