apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: core-gcp-secrets
  namespace: wg-vpn
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-admin-api-token/versions/latest"
        path: "ADMIN_API_TOKEN"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-wg-server-public-key/versions/latest"
        path: "WG_SERVER_PUBLIC_KEY"
