apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: core-gcp-secrets
  namespace: wg-vpn
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-admin-api-token/versions/latest"
        path: "ADMIN_API_TOKEN"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-node-id/versions/latest"
        path: "CORE_NODE_ID"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-wg-server-public-key/versions/latest"
        path: "WG_SERVER_PUBLIC_KEY"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-tls-server-crt/versions/latest"
        path: "server.crt"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-tls-server-key/versions/latest"
        path: "server.key"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-tls-ca/versions/latest"
        path: "ca.pem"
      - resourceName: "projects/PROJECT_NUMBER/secrets/wireguard-private-key/versions/latest"
        path: "private.key"
