apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: entry-gcp-secrets
  namespace: wg-vpn
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_NUMBER/secrets/entry-database-url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/PROJECT_NUMBER/secrets/entry-admin-api-token/versions/latest"
        path: "ADMIN_API_TOKEN"
      - resourceName: "projects/PROJECT_NUMBER/secrets/entry-jwt-signing-keys/versions/latest"
        path: "APP_JWT_SIGNING_KEYS"
      - resourceName: "projects/PROJECT_NUMBER/secrets/entry-google-oidc-client-id/versions/latest"
        path: "GOOGLE_OIDC_CLIENT_ID"
      - resourceName: "projects/PROJECT_NUMBER/secrets/entry-google-oidc-client-secret/versions/latest"
        path: "GOOGLE_OIDC_CLIENT_SECRET"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-grpc-client-tls-ca/versions/latest"
        path: "ca.pem"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-grpc-client-tls-client-crt/versions/latest"
        path: "client.crt"
      - resourceName: "projects/PROJECT_NUMBER/secrets/core-grpc-client-tls-client-key/versions/latest"
        path: "client.key"
