apiVersion: v1
kind: ServiceAccount
metadata:
  name: entry-wi
  namespace: wg-vpn
  annotations:
    iam.gke.io/gcp-service-account: entry-secrets@replace-me.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-wi
  namespace: wg-vpn
  annotations:
    iam.gke.io/gcp-service-account: core-secrets@replace-me.iam.gserviceaccount.com
