apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-vpn

resources:
  - ../prod

patchesStrategicMerge:
  - patch-core-native-driver.yaml

images:
  - name: ghcr.io/replace-me/wg-core
    newTag: stable-native-canary
