apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-vpn

resources:
  - ../prod

patchesStrategicMerge:
  - patch-core-native-driver.yaml

images:
  - name: asia-east1-docker.pkg.dev/wg-codex/wg/wg-core
    newTag: v1
