apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-vpn

resources:
  - ../../base
  - sealedsecret-entry.yaml
  - sealedsecret-core.yaml
  - sealedsecret-core-tls.yaml
  - sealedsecret-core-grpc-client-tls.yaml
  - sealedsecret-wireguard-keys.yaml

images:
  - name: asia-east1-docker.pkg.dev/wg-codex/wg/wg-entry
    newTag: v1
  - name: asia-east1-docker.pkg.dev/wg-codex/wg/wg-core
    newTag: v1
