---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-keys
  namespace: wg-vpn
spec:
  encryptedData:
    private.key: AgAcgd34K6CmOPs+evpubec0E1ibv4pHcSpU/Bdvj6BNPDQTCS6eVS7AfqX3th62SKmQ3ZIBI/0kkTBnFtwZ/OX0ke1GIhhDR1cL7VcsB9OrK6DXsLG4DYcbNTDyxo5Lm8NypBGBxT8HEmQQZD/ABLwJ76lWVLKYSrPLcTw01h3AE6MN3vIXKg21S90ErNl+DtmXS84msh4tFmCKxbSD0BpfMTxxnQLDQmEX2spfPOUxPlhVvPJGR/G4FnfH6HTQhOqLGEHvtFGv1nA8hkv09cNtIb/+rkMwruu6xtZVstPbYk1fkGgYEMMC3vCOfO1Z3dJHiJY8L239W6+uaOFHC9DCD6vDBdJFOL8Gksg+ClO9svLIcM7/rwljzcZ+iUzQ+Ib8KIjqT0vraSv+78yRynXLF2c9mV2lZcjBb6RUoCrgPugharidtiJzpTnGeOW5EVXsZu5Q+Ogl/nKXtNcizuIP+UIlf6pPtSCvcaf01vV4YsgMdfTwW+qs3xgRsWeNzwBfLYGc7L+2rlGHWfh8dABo25PHgFfiMOnj1Gw+dZAYDUutG23bUdZ0IzR8KYXic9ymf1rZUQsR6v0NTNpFW7bU1pAnvIdhjXYH2wrXdGhF/azNVFyjFp/grDez5IQvC7obPkK25Jj8dPNl3+sd6qvv73mLeO/5qvWnNgBjNyYgHU5IFcApYbLv3fdr58uMVjTGHLtkxp47kSk+0rOGpgKCipeNHtS6pEWY+Zt2bRxActjc5Gey5VGHPXDjEeo=
  template:
    metadata:
      name: wireguard-keys
      namespace: wg-vpn
