apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: core-secrets
  namespace: wg-vpn
spec:
  encryptedData:
    CORE_NODE_ID: AgReplaceMe
    ADMIN_API_TOKEN: AgReplaceMe
    WG_SERVER_PUBLIC_KEY: AgReplaceMe
    WG_PRIVATE_KEY_PATH: AgReplaceMe
    CORE_TLS_CERT_PATH: AgReplaceMe
    CORE_TLS_KEY_PATH: AgReplaceMe
    CORE_TLS_CLIENT_CA_CERT_PATH: AgReplaceMe
  template:
    metadata:
      name: core-secrets
      namespace: wg-vpn
    type: Opaque
