apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: entry-secrets
  namespace: wg-vpn
spec:
  encryptedData:
    DATABASE_URL: AgReplaceMe
    ADMIN_API_TOKEN: AgReplaceMe
    APP_JWT_SIGNING_KEYS: AgReplaceMe
    GOOGLE_OIDC_CLIENT_ID: AgReplaceMe
    GOOGLE_OIDC_CLIENT_SECRET: AgReplaceMe
  template:
    metadata:
      name: entry-secrets
      namespace: wg-vpn
    type: Opaque
