apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: core-grpc-client-tls
  namespace: wg-vpn
spec:
  encryptedData:
    ca.pem: AgReplaceMe
    client.crt: AgReplaceMe
    client.key: AgReplaceMe
  template:
    metadata:
      name: core-grpc-client-tls
      namespace: wg-vpn
    type: Opaque
