apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-keys
  namespace: wg-vpn
spec:
  encryptedData:
    private.key: AgReplaceMe
  template:
    metadata:
      name: wireguard-keys
      namespace: wg-vpn
    type: Opaque
