apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: core-tls
  namespace: wg-vpn
spec:
  encryptedData:
    server.crt: AgReplaceMe
    server.key: AgReplaceMe
    ca.pem: AgReplaceMe
  template:
    metadata:
      name: core-tls
      namespace: wg-vpn
    type: Opaque
