apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-vpn

resources:
  - ../../base
  - dev-secrets.yaml

patchesStrategicMerge:
  - patch-entry-config.yaml
  - patch-core-config.yaml

images:
  - name: ghcr.io/replace-me/wg-entry
    newTag: dev
  - name: ghcr.io/replace-me/wg-core
    newTag: dev
