apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-vpn

resources:
  - ../../base
  - dev-secrets.yaml

patchesStrategicMerge:
  - patch-entry-config.yaml
  - patch-core-config.yaml

images:
  - name: asia-east1-docker.pkg.dev/wg-codex/wg/wg-entry
    newTag: v1
  - name: asia-east1-docker.pkg.dev/wg-codex/wg/wg-core
    newTag: v1
