apiVersion: v1
kind: ConfigMap
metadata:
  name: entry-config
  namespace: wg-vpn
data:
  APP_ENV: "development"
  APP_REQUIRE_CORE_TLS: "false"
  APP_ALLOW_LEGACY_CUSTOMER_HEADER: "true"
  CORE_GRPC_URL: "http://core.wg-vpn.svc.cluster.local:50051"
